[tool.poetry]
name = "alocalproxy"
version = "0.1.0"
description = ""
authors = ["ezzye <ezzy.elliott@gmail.com>"]

[tool.poetry.dependencies]

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
